# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a0ef49f7a8868fc77f98192fa33140afdbd17bd3984f288c1e73cf95caf96d03326befc33186341aaad04b08563fece6ea552018dbb3c1e47bc3170b763706

test:
  secret_key_base: c93910ee6d9768a0e2d20fcbc24d96f1a2f6af8f84595d9fbf8c7d8114dafa13823918cfedc79bda15df0c648c636fda46e8efef9d2c9ed519976792a8e24cd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
